# Generated by Django 4.0.3 on 2023-01-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('TID', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=180)),
                ('duration', models.IntegerField()),
                ('start_date_time', models.DateTimeField()),
                ('activities', models.CharField(max_length=180)),
            ],
        ),
    ]
