# Generated by Django 4.0.3 on 2023-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=180)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
