# Generated by Django 4.0.3 on 2023-01-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('FID', models.IntegerField(primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=180)),
                ('friend_email', models.EmailField(max_length=180)),
                ('friend_age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='trip_selected_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trip'),
        ),
        migrations.AddField(
            model_name='partner',
            name='friend_selected_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.friend'),
        ),
    ]
