# Generated by Django 4.0.3 on 2023-01-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_partner_friend_selected_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date_time',
            field=models.CharField(max_length=180),
        ),
    ]
